### ISSUE TITLE
About training.py scripts

### ISSUE THREAD

**Issue by Dana136484** [BailiangJ/spine-ct-mr-registration#2]
Hello, I am reading your article. But I can't find the training and inference script files. I hope you can upload them. Thank you!

**Comment by bhatrana** [comment]
Hi Same, Can you please provide me readme instruction for training and testing this repo. Thanks

**Comment by BailiangJ** [comment]
@bhatrana @Dana136484 Thank you for your interest. I am cleaning up the code and rebuilding them based on MMCV configurations. The training and inference scripts will be soon available.

**Comment by BailiangJ** [comment]
@bhatrana @Dana136484 Dear all, the training and inference scripts are now available. Have fun.
